if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='8'
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='12'

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"hostname 4 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		"load 4 0" \
		"tmux_session_info 0 2" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		#"rainbarf 0 0" \
		"now_playing 8 13" \
		"mailcount 0 7" \
		"weatherpretty 0 7 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"date_day 3 8" \
		#"date 3 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		#"time 3 0 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
